### ISSUE TITLE
Personnel can view self profile 

### ISSUE THREAD

**Issue by trikarai** [apurbara/bara-mcp#13]
request get

expected response : 

- First Name
- Last Name
- Email
-  Bio

**Comment by apurbara** [comment]
API grouped into: /api/personnel/profile

**Comment by trikarai** [comment]
emailnya ketinggalan.

**Comment by apurbara** [comment]
https://github.com/apurbara/bara-mcp/commit/fa0797e8c9cce66166ca2c1bc4948a816b99a587
