### ISSUE TITLE
Personnel (as consultant) participant team type not displaying.

### ISSUE THREAD

**Issue by trikarai** [apurbara/bara-mcp#15]
team type not returned on response.

`{"data":{"total":1,"list":[{"id":"aa7ca896-9f04-4f98-b236-9ad91fceedb6","enrolledTime":"2020-09-10 17:20:01","active":true,"note":null,"user":null,"client":{"id":"7bbde53f-da7d-4155-8634-a8d7bd69a170","name":"Tri Sutrisno"}}]},"meta":{"code":200,"type":"OK"}}`

**Comment by apurbara** [comment]
https://github.com/apurbara/bara-mcp/commit/fa0797e8c9cce66166ca2c1bc4948a816b99a587
