### ISSUE TITLE
manager upload file folder not created

### ISSUE THREAD

**Issue by trikarai** [apurbara/bara-mcp#16]
upload file response : 

`{
  "data": {
    "id": "6c695b8e-a138-413f-9e0a-f72a4236471d",
    "path": "\/firm_d34be82f-0cc0-4aaf-a887-f0f204e805ce\/imege.jpg",
    "size": 1894684
  },
  "meta": {
    "code": 201,
    "type": "Created"
  }
}`

but no folder and file found on storage

**Comment by apurbara** [comment]
https://github.com/apurbara/bara-mcp/commit/968d9dee2cc2d0fc2bf0015ad402c399e67f3e1c
