### ISSUE TITLE
Firm profile return fileinfoId

### ISSUE THREAD

**Issue by trikarai** [apurbara/bara-mcp#18]
api : **api/manager/firm-profile**
#14 
respone : 
`{"data: {"name":"barapraja","domain":"http:\/\/barapraja.com","mailSenderAddress":"noreply@barapraja.com","mailSenderName":"Bara Mail","logoPath":"\\firm_d34be82f-0cc0-4aaf-a887-f0f204e805ce\\08b18153dbeb4feeb0f7aed7392c3be5_Jeniuslogo.png","displaySetting":""},"meta":{"code":200,"type":"OK"}}`

expected fileinfoid only path found

**Comment by apurbara** [comment]
https://github.com/apurbara/bara-mcp/commit/5e45b97a3e36d47250e82de5e2c824f180120098
