### ISSUE TITLE
Need Worksheet Form description in worksheet detail (show) response

### ISSUE THREAD

**Issue by trikarai** [apurbara/bara-mcp#7]
**API** : `api/client/program-participations/b8a8971b-1b3a-48d9-a749-d594e948b727/worksheets/d4eac54f-a326-4aeb-ab27-0a41b67cc332` 

**Expected** : 

`....  "mission": {
      "id": "87afc446-66e2-4c7b-9b85-d3de017397d2",
      "name": "Value Proposition",
      "worksheetForm": {
        "id": "35f85121-0597-4ad7-bb84-9bf9e3205370",
"name": "form name" , "description":  "form description" 
      } ...`

**reason**: 

setting to render as canvas saved as json string in description.

**Comment by apurbara** [comment]
https://github.com/apurbara/bara-mcp/commit/474cd9e34233bf4f64be1562a221f97e653d8634

**Comment by trikarai** [comment]
kenapa di close :(

**Comment by apurbara** [comment]
https://github.com/apurbara/bara-mcp/commit/377f3b34f50fd45b633c578a6cb987ee760cf75c
