### ISSUE TITLE
Firm Manager : Error on Mission  get (ShowAll)

### ISSUE THREAD

**Issue by trikarai** [apurbara/bara-mcp#8]
API : `api/manager/programs/fec49ea1-62ad-415a-8b3a-221bca786476/missions`

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function Query\Application\Service\Firm\Program\MissionView::showAll(), 3 passed in C:\xampp\htdocs\bara-mcp\app\Http\Controllers\Manager\Program\MissionController.php on line 96 and exactly 4 expected in C:\xampp\htdocs\bara-mcp\src\Query\Application\Service\Firm\Program\MissionView.php:35 Stack trace: #0 C:\xampp\htdocs\bara-mcp\app\Http\Controllers\Manager\Program\MissionController.php(96): Query\Application\Service\Firm\Program\MissionView->showAll(Object(Firm\Application\Service\Firm\Program\ProgramCompositionId), 1, 25) #1 [internal function]: App\Http\Controllers\Manager\Program\MissionController->showAll('fec49ea1-62ad-4...') #2 C:\xampp\htdocs\bara-mcp\vendor\illuminate\container\BoundMethod.php(33): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\bara-mcp\vendor\illuminate\container\Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #4 C:\xampp\htdocs\bara-mcp\vendor\illuminate\container\BoundMethod.php(91): Illumi in C:\xampp\htdocs\bara-mcp\src\Query\Application\Service\Firm\Program\MissionView.php on line 35

Fatal error: Uncaught Error: Call to undefined method Laravel\Lumen\Application::handleException() in C:\xampp\htdocs\bara-mcp\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php:67 Stack trace: #0 C:\xampp\htdocs\bara-mcp\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown() #1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}() #2 {main} thrown in C:\xampp\htdocs\bara-mcp\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php on line 67`

**Comment by apurbara** [comment]
https://github.com/apurbara/bara-mcp/commit/40f9c5de28089560ac2274c1a782f6188050cbe0
