### ISSUE TITLE
return mission (show) by Position expected same return as mission 

### ISSUE THREAD

**Issue by trikarai** [apurbara/bara-mcp#9]
**API** :  `client/program-participations/b8a8971b-1b3a-48d9-a749-d594e948b727/missions/by-position/2`

**return** : `{
  "data": {
    "id": "87afc446-66e2-4c7b-9b85-d3de017397d2",
    "name": "Value Proposition",
    "description": "this is vp ",
    "position": "2",
    "parent": {
      "id": "f62331a7-d22a-47c0-b475-26d4a7a90d78",
      "name": "Mission 1",
      "parent": null
    },
    "worksheets": [
      {
        "id": "d4eac54f-a326-4aeb-ab27-0a41b67cc332",
        "name": "BP",
        "parent": {
          "id": "6ea377d8-dfad-4ce0-b071-6998c8a9c472",
          "name": "This is worksjksdj",
          "parent": null
        }
      }
    ]
  },
  "meta": {
    "code": 200,
    "type": "OK"
  }
}`

**expected same as** 

**api** `client/as-program-participant/883ac9c1-2f76-4470-a04e-dc0fcbebe094/fec49ea1-62ad-415a-8b3a-221bca786476/missions/87afc446-66e2-4c7b-9b85-d3de017397d2`

**return** 

`{
  "id": "87afc446-66e2-4c7b-9b85-d3de017397d2",
  "name": "Value Proposition",
  "description": "this is vp ",
  "position": "2",
  "worksheetForm": {
    "name": "Value Proposition",
    "description": "{\"renderAs\":true,\"description\":\"this is vp\"}",
    "stringFields": [],
    "integerFields": [],
    "textAreaFields": [
      {
        "id": "13294ea5-496b-4bef-b96a-72770d8dfc12",
        "name": "Value Proposition",
        "description": "",
        "position": "1 \/ 1 \/ 2 \/ 3",
        "mandatory": false,
        "defaultValue": "",
        "minValue": 10,
        "maxValue": 350,
        "placeholder": ""
      },
      {
        "id": "3feed379-5579-4e18-a82e-2c561d65cfce",
        "name": "Pain Reliever",
        "description": "",
        "position": "3 \/ 2 \/ 4 \/ 3",
        "mandatory": false,
        "defaultValue": "",
        "minValue": 10,
        "maxValue": 350,
        "placeholder": ""
      },
      {
        "id": "56eb31a0-41a0-4b36-b07a-6f7387d939ff",
        "name": "Customer Segment",
        "description": "",
        "position": "1 \/ 3 \/ 2 \/ 5",
        "mandatory": false,
        "defaultValue": "",
        "minValue": 10,
        "maxValue": 350,
        "placeholder": ""
      },
      {
        "id": "76beff20-bd2d-4f0e-862d-191e7955b37f",
        "name": "Gain",
        "description": "",
        "position": "2 \/ 3 \/ 3 \/ 4",
        "mandatory": false,
        "defaultValue": "",
        "minValue": 10,
        "maxValue": 350,
        "placeholder": ""
      },
      {
        "id": "7ccdce49-7106-46e1-9352-72a8474a1fd0",
        "name": "Gain Creator",
        "description": "",
        "position": "2 \/ 2 \/ 3 \/ 3",
        "mandatory": false,
        "defaultValue": "",
        "minValue": 10,
        "maxValue": 350,
        "placeholder": ""
      },
      {
        "id": "87e9eb59-d9e6-491a-89a1-40c6ff56d563",
        "name": "Product Concept",
        "description": "",
        "position": "2 \/ 1 \/ 4 \/ 2",
        "mandatory": false,
        "defaultValue": "",
        "minValue": 10,
        "maxValue": 350,
        "placeholder": ""
      },
      {
        "id": "c911084e-4f1a-4a91-b3f7-5c4f24085478",
        "name": "Pain",
        "description": "",
        "position": "3 \/ 3 \/ 4 \/ 4",
        "mandatory": false,
        "defaultValue": "",
        "minValue": 10,
        "maxValue": 350,
        "placeholder": ""
      },
      {
        "id": "d5a8da06-0d1e-4419-8c9e-154cecf73123",
        "name": "Job",
        "description": "",
        "position": "2 \/ 4 \/ 4 \/ 5",
        "mandatory": false,
        "defaultValue": "",
        "minValue": 10,
        "maxValue": 350,
        "placeholder": ""
      }
    ],
    "attachmentFields": [],
    "singleSelectFields": [],
    "multiSelectFields": [],
    "id": "35f85121-0597-4ad7-bb84-9bf9e3205370"
  },
  "parent": {
    "id": "f62331a7-d22a-47c0-b475-26d4a7a90d78",
    "name": "Mission 1",
    "description": "this is mission 1",
    "position": "1"
  }
}`

**Comment by apurbara** [comment]
https://github.com/apurbara/bara-mcp/commit/f6741913802ebdc804904613c8769a8a5ed7a9f7
